### ISSUE TITLE
Feature Request of auto reconnecting to GCR tunnels

### ISSUE THREAD

**Issue by frinkleko** [JeffreyXiang/MSRA-Intern-s-Toolkit#1]
Thank you for your excellent work.

Recently, I was suffering about very frequent disconnection with GCR tunnel. I was wondering if there is a need to add one new feature about auto reconnecting to selected GCR tunnels. If this feature has its own necessity of existence, I would like to further discuss about its appearance for design. My suggestion is as follows:

![image](https://github.com/JeffreyXiang/MSRA-Intern-s-Toolkit/assets/32212221/98365753-1a7d-43d4-a44e-75229e7076e9)

Adding one checkbox under each GCR machine and one `MaxTrials` number represents max attempts times for reconnecting (maybe this could be just a fixed value in default and have no need for displaying or changing by user). In implementation, we just need to add few lines about detecting connection status and recall the building connection function within `MaxTrial` attempts. I think it should look like a simple warper function based on current codes.

If this sounds great, I am planning to open a pull request to work on it or just request this feature from you😘. Or I can just fix my disconnection problem from IT Support🤣.

**Comment by JeffreyXiang** [comment]
Hi!

Thanks for your usage of this tool.

The feature you requested is good and necessary. I am planning to add it to the project in the next update.

My current plan is to retry connecting when the tunnel is closed unexpectedly for a fixed max trial (e.g., 3 should be enough). This maxtrial number can be modified through VScode extension settings. Setting a different number for each tunnel and show it in the UI may not be necessary for simplicity.

**Comment by JeffreyXiang** [comment]
The requested feature is added in commit 3a7487b.
Published in version 1.3.3
